import Link from 'next/link';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
  console.log("montando layout");

  return (
    <html lang="en">
      <body>
        {/* Menu fixo no layout */}
        <div style={{ background: "#ddd", padding: "10px" }}>
          <Link href="/">Home</Link> | 
          <Link href="/novarota">Nova Rota</Link> |  
          <Link href="/novarota/tabela">Tabela</Link> |  
          <Link href="/risada">Risada</Link> |  
          <Link href="/rota1">Rota1</Link> |  
          <Link href="/rota2">Rota2</Link> |
          <Link href="/movies">movies</Link> |
          <Link href="clientServerMovies">clientServerMovies</Link>
        </div>

        {/* Aqui será renderizado o conteúdo das páginas */}
        {children}
      </body>
    </html>
  );
}
